server:
  port: 8000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fileConvertor
    username: fileConvertor
    password: fileConvertor
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1
